# Site settings
title: lihsmi.ch
email: mimi@kaktusteam.de
description: > # this means to ignore newlines until "baseurl:"
  Blog on (PHP) programming, Vagrant, Chef, Solr, TYPO3 and some other
  stuff.
baseurl: ""
url: "http://michaellihs.github.io"
twitter_username: kaktusmimi
github_username: michaellihs
slideshare_username: mimiknoll

# Build settings
markdown: kramdown
