# Site settings
title: lihsmi.ch
email: mimi@kaktusteam.de
description: > # this means to ignore newlines until "baseurl:"
  Blog on (PHP) programming, Vagrant, Chef, Solr, TYPO3 and some other
  stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://michaelknoll.github.io" # the base hostname & protocol for your site
twitter_username: kaktusmimi
github_username: michaelknoll
slideshare_username: mimiknoll

# Build settings
markdown: kramdown
